#!/usr/bin/env bash

set_pkgmgr() {
    local distro="$1"

    case "$distro" in
        "artix" | "arch")
            export pkgmgr="pacman"
            ;;
        "debian" | "ubuntu")
            export pkgmgr="apt"
            ;;
        "rocky")
            export pkgmgr="dnf"
            ;;
    esac
}

update_pkgmgr() {
    clear

    case "$pkgmgr" in
        "dnf")
            # `dnf` does not have a command to "update package repositories"
            return 0
            ;;
        *)
            echo -e "[INFO]: Updating packages repositories with the newest package lists.\n"
            echo -e "[INFO]: This command will display output, so the user can observe the process.\n"
            ;;
    esac

    case "$pkgmgr" in
        "pacman")
            pacman -Sy
            ;;
        "apt")
            apt update
            ;;
    esac

    echo -e "\n[INFO]: Package repositories have been successfully updated!"
}

upgrade_pkgs() {
    clear
    echo -e "[INFO]: Upgrading installed packages to their latest versions.\n"
    echo -e "[INFO]: This command will display output, so the user can observe the process.\n"

    case "$pkgmgr" in
        "pacman")
            pacman -Syy
            ;;
        "apt")
            apt upgrade
            ;;
        "dnf")
            dnf update
            ;;
    esac

    echo -e "\n[INFO]: Installed packages have been successfully upgraded!"
}

install_pkg() {
    local pkg="$1"

    echo "[INFO]: Installing \`$pkg\`."

    case "$pkgmgr" in
        "pacman")
            pacman --noconfirm --needed -S "$pkg" > /dev/null 2>&1
            ;;
        "apt")
            DEBIAN_FRONTEND=noninteractive apt install -y "$pkg" > /dev/null 2>&1
            ;;
        "dnf")
            dnf install -y "$pkg" > /dev/null 2>&1
            ;;
    esac
}

install_aur_pkg() {
    case "$aur_helper" in
        "yay")
            local pkg="$1"

            echo "[INFO]: Installing \`$pkg\` via the AUR."
            sudo -u "$user_name" $aur_helper -S --noconfirm "$pkg" > /dev/null 2>&1
            ;;
        *)
            return 0
            ;;
    esac
}

loop_install_pkg() {
    local pkgs=("$@")

    for ((p=0; p<"${#pkgs[@]}"; p++)); do
        install_pkg "${pkgs[p]}" \
            || echo "[ERROR]: Failed to install \`${pkgs[p]}\`." >> "${WORK_DIR}/pkg_fail.txt"
    done
}

loop_install_aur_pkg() {
    local pkgs=("$@")

    for ((p=0; p<"${#pkgs[@]}"; p++)); do
        install_aur_pkg "${pkgs[p]}" \
            || echo "[ERROR]: Failed to install \`${pkgs[p]}\`." >> "${WORK_DIR}/pkg_fail.txt"
    done
}
