#!/usr/bin/env bash

get_os_release() {
    while read -r line; do
        case $line in
            "ID="* )
                export iso_distro="${line##*=}"
                iso_distro="${iso_distro//\"}"
                ;;
            "BUILD_ID="* | "VERSION_CODENAME="* | "VERSION_ID="* )
                export iso_release="${line##*=}"
                iso_release="${iso_release//\"}"
                ;;
        esac

        # return, if all values are set
        if [[ "$iso_release" ]] && [[ "$iso_distro" ]]; then
            return 0
        fi
    done < "/etc/os-release"
}

get_ram_total() {
    export ram_total=0

    while read -r line; do
        # If the line is equal to "Memory Device", flag as a memory device
        if [[ "$line" == "Memory Device" ]]; then
            local flag_ram=true
            continue
        fi

        # If `flag_ram` is `false`, skip to the next line
        if [[ "$flag_ram" == false ]]; then
            continue
        fi

        # Handle a memory device's size
        if [[ "$line" =~ "Size:" ]]; then
            # After this conditional, stop looking at this specific memory device
            flag_ram=false

            # If the "size" is "No Module Installed", skip to next line
            if [[ "$line" =~ "No Module Installed" ]]; then
                continue
            fi

            # Remove the "left-side" excess
            local ram_size="${line##*Size: }"

            # Get the RAM unit for the memory device
            local ram_unit="${line##* }"

            # Remove the "right-side" excess
            ram_size="${ram_size%% *}"

            # Add `ram_size` for the memory device to the running total
            ram_total="$((ram_total + ram_size))"
        fi
    done < <(dmidecode -t memory)

    # Handle the units of RAM
    case "$ram_unit" in
        *G*)
            ;;
        *M*)
            # Define `ram_total` as `ram_in_mb`
            local ram_in_mb="$ram_total"

            # Divide by 1000:
            #     8000 will become 8
            #     7900 will become 7
            local ram_in_gb="$((ram_in_mb / 1000))"

            # If there was a remainder, increase `ram_in_gb` by 1:
            if (((ram_in_mb % 1000) > 0)); then
                ram_in_gb="$((ram_in_gb + 1))"
            fi

            ram_total="$ram_in_gb"
            ;;
    esac
}

get_firmware() {
    if [[ -f "/sys/firmware/efi" ]]; then
        export firmware=uefi
    #elif [[ $(mount | grep -q "efi") ]]; then
    #    export firmware=uefi
    else
        export firmware=bios
    fi
}

get_available_disks() {
    export available_disks=()

    while read -r line; do
        if [[ "$line" =~ "disk" ]]; then
            read -r dev a b size c <<< "$line"
            local unit="${size//[0-9]}"
            local num="${size//[^0-9]}"
            available_disks+=("$dev | $num ${unit}B")
        fi
    done < <(lsblk)
}
