#!/usr/bin/env bash

ask_lvm_name() {
    # Skip if no encryption
    if [[ "$encryption" == "no" ]]; then
        return 0
    fi

    export lvm_name=""
    clear
    cat << EOF
LVM NAME:

Please enter the name for the encrypted LVM.

If no name is given, then the script will set \`cryptlvm\` as the LVM's name.
EOF
    read -p "> " lvm_name

    if ! [[ "$lvm_name" ]]; then
        lvm_name="cryptlvm"
        return 0
    fi

    # put user in loop until the LVM name is compliant
    while ! [[ "$lvm_name" =~ ^[a-z]*$ ]]; do
        clear
        cat << EOF
LVM NAME:

Invalid LVM name.

Please provide a LVM name using lowercase letters only.
EOF
        read -p "> " lvm_name
    done
}

ask_user_name() {
    export user_name=""
    clear
    cat << EOF
USERNAME:

Please enter a name for the user.
EOF
    read -p "> " user_name

    # put user in loop until the username is compliant
    while ! [[ "$user_name" =~ ^[A-Za-z][A-Za-z_.-]*[A-Za-z]*$ ]] || ! [[ "$user_name" ]]; do
        clear
        cat << EOF
USERNAME:

Invalid username.

Please provide a username using letters only.

\`-\`, \`_\`, and \`.\` can be used for any character but the first and last.
EOF
        read -p "> " user_name
    done
}

ask_pass_master() {
    export pass_master=""
    clear
    cat << EOF
MASTER PASSWORD:

Please enter a master password.

The password entered will become the password for both the user account (\`${user_name}\`) and the \`root\` account.

If disk encryption was selected, it will also be set as the encryption password.
EOF
    read -s -p "> " pass_master
    echo -e "\n\nPlease retype the master password."
    read -s -p "> " pass_master_check

    # put user in loop until the two "master password" entries agree
    while ! [[ "$pass_master" == "$pass_master_check" ]] || ! [[ "$pass_master" ]]; do
        clear
        cat << EOF
MASTER PASSWORD:

The passwords entered do not match each other, or were left blank.

Please enter the master password again.
EOF
        read -s -p "> " pass_master
        echo -e "\n\nPlease retype the master password."
        read -s -p "> " pass_master_check
    done
}

ask_hostname() {
    export host_name=""
    clear
    cat << EOF
HOSTNAME:

Please enter a hostname.
EOF
    read -p "> " host_name

    # put user in loop until the hostname is compliant
    while ! [[ "$host_name" =~ ^[a-z][a-z0-9_.-]*[a-z0-9]*$ ]] || ! [[ "$host_name" ]]; do
        clear
        cat << EOF
HOSTNAME:

Invalid hostname.

Please provide a hostname using lowercase letters only.

Numbers can be used for any character except the first.

\`-\`, \`_\`, and \`.\` can be used for any character but the first and last.
EOF
        read -p "> " host_name
    done
}

ask_local_domain() {
    export local_domain=""
    clear
    cat << EOF
LOCAL DOMAIN:

Please enter a local domain.

If no domain is given, then the script will set \`local\` as the local domain name.
EOF
    read -p "> " local_domain

    if ! [[ "$local_domain" ]]; then
        local_domain="local"
        return 0
    fi

    # put user in loop until the local domain is compliant
    while ! [[ "$local_domain" =~ ^[a-z]*$ ]] || ! [[ "$local_domain" ]]; do
        clear
        cat << EOF
LOCAL DOMAIN:

Invalid local domain.

Please provide a domain using lowercase letters only.
EOF
        read -p "> " local_domain
    done
}

get_user_input() {
    ask_lvm_name
    ask_user_name
    ask_pass_master
    ask_hostname
    ask_local_domain
}
