#!/usr/bin/env bash

setup_vim() {
    local pkgs=("vim")
    loop_install_pkg "${pkgs[@]}"

    echo "[INFO]: Configuring \`vim\`."
    sudo -u "$user_name" mkdir -p "/home/${user_name}/.vim/autoload"

    sudo -u "$user_name" curl \
        -Ls "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim" \
        -o "/home/${user_name}/.vim/autoload/plug.vim"

    sudo -u "$user_name" vim -c "PlugInstall|q|q"

    # Symlink the Vim configs into the root user's directory
    ln -s "/home/${user_name}/.local/src/vim" "/root/.vim"
}
