#!/usr/bin/env bash

install_zsh() {
    local pkgs=("zsh")
    loop_install_pkg "${pkgs[@]}"
}

install_zsh_highlighting() {
    case "$install_distro" in
        "artix" | "arch")
            local pkgs=("zsh-fast-syntax-highlighting-git")

            loop_install_aur_pkg "${pkgs[@]}"
            return 0
            ;;
        "debian" | "ubuntu" | "rocky")
            local pkgs=("zsh-syntax-highlighting")
            ;;
    esac

    loop_install_pkg "${pkgs[@]}"
}

config_zsh() {
    echo "[INFO]: Configuring \`zsh\`."

    sudo -u "$user_name" git clone \
        --depth=1 \
        https://github.com/romkatv/powerlevel10k \
        "$REPODIR/powerlevel10k" \
        > /dev/null 2>&1

    local fonts=(
        "MesloLGS_NF_Regular.ttf"
        "MesloLGS_NF_Bold.ttf"
        "MesloLGS_NF_Italic.ttf"
        "MesloLGS_NF_Bold_Italic.ttf"
    )

    mkdir -p /usr/local/share/fonts/m

    for ((j=0; j < "${#fonts[@]}"; j++)); do
        local FONT="${fonts[j]}"

        if ! [[ -e "/usr/local/share/fonts/m/${FONT}" ]]; then
            local WEBFONT="${FONT//_/%20}"

            curl \
                -Ls "https://github.com/romkatv/powerlevel10k-media/raw/master/$WEBFONT" \
                -o "/usr/local/share/fonts/m/${FONT}"
        fi
    done

    chsh -s /bin/zsh "$user_name" > /dev/null 2>&1
}

setup_zsh() {
    install_zsh
    install_zsh_highlighting
    config_zsh
}
