#!/usr/bin/env bash

completion_screen() {
    readarray banner < "${WORK_DIR}/src/banner.txt"
    clear

    local DURATION="$SECONDS"
    local TIME_COMPLETION="$((DURATION / 60)) minutes and $((DURATION % 60)) seconds"

    cat << EOF

 ${banner[@]}

    Provided there were no hidden errors, \`linux-installer\` completed successfully!

    All packages should be installed, and all configurations should be properly set.

    However, all "package installation failures" should have been recorded in the following file:

        /root/.local/src/linux-installer/pkg_fail.txt

    Or, if still within the ISO:

        /mnt/root/.local/src/linux-installer/pkg_fail.txt

    Enjoy the new Linux installation!

    This installation took $TIME_COMPLETION to complete, btw.

EOF

read -p "    Press \"Enter\" to continue..."
echo
}
